variable "application" {}
variable "api_gateway_vpc_endpoint_ids" {}
variable "api_gateway_configuration" {}
variable "api_gateway_endpoint_configuration" {}
variable "lambda_uri" {}
variable "loadbalancer_uri" {}
variable "lambda_authorizer_config" {}
variable "aws_account_id" {}
variable "authorization_config" {}